import Head from "next/head";
import Image from "next/image";
import  Hero  from "../components/Hero";
import { SliderData } from "../components/SliderData"
import  Slider  from "../components/Slider";
import Instagram from "../components/Instagram";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Photography Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero
        heading="Captur Photography"
        message="I capture moments in nature and keep them alive."
      />
      <Slider slides={SliderData} />
      <Instagram />
    </div>
  );
}
// "Captur Photography"
// 'I capture moments in nature and keep them alive.'